package dev.mantlekeep.springboot.ai.agent;

/**
 * The measured cost of one harness invocation, as reported by the Claude Code CLI's
 * terminating {@code result} line.
 *
 * <p>This exists so a governed action can carry its price: the loop product records these
 * numbers alongside the draft they paid for, which is what turns "every governed action is
 * audited" into "every governed action is audited <em>with its measured cost</em>". Without
 * it the product burns tokens invisibly and no one can bill, budget, or cap.
 *
 * <p>It lives in the AI starter rather than {@code mantlekeep-spring-boot-core} deliberately:
 * the shape is CLI-specific (cache read/creation tiers, a US-dollar figure, a wall-clock
 * duration). Hoisting it into core would put a vendor-shaped record on the sealed generic
 * surface, where a different LLM adapter would have to fake fields it cannot measure. Core
 * stays LLM-free; when a second adapter arrives and a common denominator is actually known,
 * a generic port type can be introduced then — additively.
 *
 * <p>All token counts and the cost are non-negative; {@link #NONE} represents "the CLI never
 * reported usage" (an early error, or a stream that ended before the result line).
 *
 * @param inputTokens              fresh (uncached) prompt tokens billed at full rate
 * @param outputTokens             tokens generated by the model
 * @param cacheReadInputTokens     prompt tokens served from the cache (billed at ~0.1x)
 * @param cacheCreationInputTokens prompt tokens written to the cache (billed at ~1.25x)
 * @param totalCostUsd             the CLI's own cost figure for the run, in US dollars
 * @param durationMillis           wall-clock duration of the run as reported by the CLI
 */
public record Usage(
        long inputTokens,
        long outputTokens,
        long cacheReadInputTokens,
        long cacheCreationInputTokens,
        double totalCostUsd,
        long durationMillis) {

    /** No usage was reported — the run errored early, or produced no result line. */
    public static final Usage NONE = new Usage(0L, 0L, 0L, 0L, 0.0d, 0L);

    /**
     * Every prompt token the run consumed, whichever tier it was billed at. Handy for a
     * single "tokens in" column; the per-tier fields remain for cost attribution.
     */
    public long totalInputTokens() {
        return inputTokens + cacheReadInputTokens + cacheCreationInputTokens;
    }

    /** Whether the CLI actually reported anything — {@code false} for {@link #NONE}. */
    public boolean isPresent() {
        return !equals(NONE);
    }
}
